### ISSUE TITLE
Request to make the repository private

### ISSUE THREAD

**Issue by lucat1** [MihhailSokolov/ACMEclient#1]
Hi,

I'm reaching out on behalf of the NetSec course staff at ETH Zürich.
I'm this year's NetSec Project's Student Assistant.
I have to kindly ask you to make this repository private in order to avoid
providing hints to students who are taking the NetSec course this year.
Thank you for the understanding,

Best,
Luca

**Comment by MihhailSokolov** [comment]
Hi @lucat1 
Sure, I can make it private.
Will it have to stay private forever or will I be able to make it public again later?

**Comment by lucat1** [comment]
Hi @MihhailSokolov 
Thank you for your understanding. It just has to stay private for the duration of the project.
This means that you can make it public again on the the 9 of November 2024.
